spring:
  application:
    name: order-processing-service



  data:
    mongodb:
      uri: mongodb://localhost:27017/order_processing_db?maxPoolSize=50&minPoolSize=5&connectTimeoutMS=10000&socketTimeoutMS=0&maxIdleTimeMS=300000

